import type { UserProfile } from "@/lib/types";

export const apiBase = "/api";

export const languageOptions = {
  en: { label: "English", shortLabel: "EN", locale: "en" },
  pt: { label: "Português", shortLabel: "PT", locale: "pt" },
  es: { label: "Español", shortLabel: "ES", locale: "es" },
  it: { label: "Italiano", shortLabel: "IT", locale: "it" },
  zh: { label: "中文（简体）", shortLabel: "中文", locale: "zh-Hans" },
};

export const translations = {
  en: {
    languageSelectLabel: "Select language",
    languageOptionsLabel: "Language options",
    brandAriaLabel: "IGATES home",
    brandAlt: "IGATES Fund Intelligence logo",
    navWhy: "Why IGATES",
    navVerifiedManagers: "Verified Managers",
    navManagers: "Fund Manager",
    navFamily: "Family Offices",
    navLearn: "Learn",
    navContact: "Contact",
    navAuthSignup: "Sign Up / Log In",
    navAuthMaster: "Master Dashboard",
    navAuthManager: "Manager Dashboard",
    navAuthProfile: "My Profile",
    heroEyebrow: "Institutional access",
    heroTitle: "Connecting capital with verified managers",
    heroLead: "Institutional infrastructure to access managed funds with professional standards.",
    heroCtaInvestor: "Request institutional access",
    heroCtaManager: "Apply as a manager",
    heroTrust1: "Operate with regulated entities",
    heroTrust2: "Segregated accounts and protected funds",
    heroTrust3: "Verified monthly reporting",
    heroPerformanceLabel: "YTD performance",
    heroVolatilityLabel: "Volatility",
    heroMaxDrawdownLabel: "Max drawdown",
    heroRiskLabel: "Risk",
    heroRiskLevel: "Medium-Low",
    heroAumLabel: "Verified AUM",
    heroManagersLabel: "With 10 managers",
    heroMetricsLabel: "Consolidated metrics",
    heroMetricsCta: "View full statistics",
    whyEyebrow: "Strategic purpose",
    whyTitle: "Why IGATES exists?",
    whyLead: "A curated bridge between qualified capital and private managers with verified track records.",
    whyCard1Title: "Audited accounts and verified capital",
    whyCard1Body:
      "We work exclusively with funds that have over 12 months of audited history, operating real capital with custodians and regulated entities.",
    whyCard1Spec: "VERIFICATION",
    whyCard1Alt: "Track record verification graphic",
    whyCard2Title: "Ongoing support and risk control",
    whyCard2Body:
      "Active support during onboarding and throughout the investment cycle. We deliver monthly reporting and adjust risk levels in consensus between investors and private managers.",
    whyCard2Spec: "RISK OVERSIGHT",
    whyCard2Alt: "Continuous support and risk control graphic",
    whyCard3Title: "Execution infrastructure",
    whyCard3Body:
      "Operating architecture ready for broker-grade integrations, with execution and liquidity flows coordinated under institutional standards.",
    whyCard3Spec: "EXECUTION RAILS",
    whyCard3Alt: "Global managers and diversified strategies graphic",
    whyFooterNote:
      "IGATES is the verification and reporting layer; execution and custody occur via integrated brokers.",
    learnEyebrow: "Daily forum",
    learnTitle: "Learning & community",
    learnLead: "Briefings and highlights to keep you informed every day.",
    learnPost1Title: "Allocation radar: credit and macro trends",
    learnPost1Time: "Today",
    learnPost1Body:
      "Highlighted threads with allocators on multi-asset liquidity, duration risk, and macro hedges.",
    learnPost2Title: "Manager spotlight: digital-asset neutrality",
    learnPost2Time: "Updated daily",
    learnPost2Body:
      "Daily summary of risk notes and operational updates from the digital-assets desk.",
    learnPost3Title: "Community brief: operations and compliance",
    learnPost3Time: "This week",
    learnPost3Body: "Q&A on onboarding checklists, data rooms, and audit readiness.",
    complianceEyebrow: "Compliance first",
    complianceTitle: "Regulatory-grade controls at every stage.",
    complianceBody:
      "SOC2-ready infrastructure, geo-fenced data residency, and layered permissions keep sensitive information protected.",
    complianceIdentityTitle: "Identity and access",
    complianceIdentityBody: "Multi-factor authentication, SSO/SAML, and secure vaults for documents and NDAs.",
    complianceMonitoringTitle: "Monitoring",
    complianceMonitoringBody: "Automated audit trails, threshold alerts, and encryption in transit and at rest.",
    complianceGovernanceTitle: "Governance",
    complianceGovernanceBody: "Preconfigured policies aligned to institutional due diligence standards.",
    contactEyebrow: "Let's talk",
    contactTitle: "Start your access process.",
    contactLead:
      "Tell us about your mandate or strategy. Our team will coordinate data rooms, due diligence requests, and secure access.",
    contactResponseLabel: "Response time",
    contactResponseMetric: "< 24 hours",
    contactCoverageLabel: "Coverage",
    contactCoverageMetric: "Global allocators",
    contactSecurityLabel: "Security",
    contactSecurityMetric: "SOC2-ready",
    contactNameLabel: "Name",
    contactNamePlaceholder: "Your full name",
    contactEmailLabel: "Email",
    contactEmailPlaceholder: "you@firm.com",
    contactRoleLabel: "Role",
    contactRoleAria: "Role",
    contactRolePlaceholder: "Select your role",
    contactRoleAllocator: "Allocator / Investor",
    contactRoleManager: "Fund Manager",
    contactRoleOps: "Operations / Compliance",
    contactNotesLabel: "Notes",
    contactNotesPlaceholder: "Mandate size, strategies, timing",
    contactSubmit: "Request Advisory",
    contactStatusSending: "Sending...",
    contactStatusSuccess: "We received your request. Our team will respond shortly.",
    contactStatusError: "Unable to submit right now. Please confirm the backend is running.",
    formNameLabel: "Name",
    formNamePlaceholder: "Your full name",
    formFirmLabel: "Firm",
    formFirmPlaceholderFamily: "Family office name",
    formFirmPlaceholderManager: "Firm name",
    formStrategyLabel: "Strategy Type",
    formStrategyPlaceholderFamily: "Macro, Credit, Digital Assets...",
    formStrategyPlaceholderManager: "Credit, Macro, Digital Assets...",
    formAumLabel: "AUM",
    formAumPlaceholderFamily: "$500M",
    formAumPlaceholderManager: "$250M",
    formEmailLabel: "Email",
    formEmailPlaceholderFamily: "you@office.com",
    formEmailPlaceholderManager: "you@firm.com",
    formNotesLabel: "Notes",
    formNotesPlaceholderFamily: "Mandate size, target strategies, timelines",
    formNotesPlaceholderManager: "Mandate focus, timelines, targets",
    familyFormSubmit: "Request Access",
    formSubmit: "Apply as a Manager",
    formStatusSending: "Sending...",
    formStatusSuccess: "Submitted!",
    formStatusError: "Unable to submit right now.",
    fundsLoading: "Loading verified funds...",
    fundsLoadError: "Unable to load funds. Start the backend server.",
    fundsEmpty: "No verified funds available.",
    fundsStatusVerified: "Verified",
    fundsSummaryDefault: "Manager pending verification.",
    fundsHighlight1: "Verified track record",
    fundsHighlight2: "Monthly reporting",
    fundsHighlight3: "Due diligence ready",
    fundsLabelAum: "AUM",
    fundsLabelYtd: "YTD",
    fundsLabelRisk: "Risk",
    fundsLabelStrategyFallback: "Multi-Strategy",
    fundsLabelDomicileFallback: "Global",
    insightsLoading: "Loading intelligence feed...",
    insightsLoadError: "Unable to load insights. Start the backend server.",
    footerTagline: "Elite connectivity for fund managers and qualified capital.",
    footerPlatform: "Platform",
    footerOverview: "Overview",
    footerFeaturedFunds: "Featured Funds",
    footerIntelligence: "Intelligence",
    footerCompany: "Company",
    footerAbout: "About",
    footerCompliance: "Compliance",
    footerCareers: "Careers",
    footerContact: "Contact",
    footerRequestCall: "Request a Call",
    footerInvestorRelations: "Investor Relations",
    footerRights: "© 2024 IGATES. All rights reserved.",
    footerPrivacy: "Privacy & Security",
    managersHeroEyebrow: "For Managers",
    managersHeroTitle: "Purpose-built distribution for elite strategies.",
    managersHeroLead: "Connect with verified global allocators using IGATES’ institutional infrastructure.",
    managersHeroCta: "Apply as a Manager",
    managersHeroTrust1: "Allocator coverage across macro, credit, digital assets",
    managersHeroTrust2: "SOC2-ready data exchange",
    managersCardLabel1: "Live mandates",
    managersCardCopy1: "Qualified allocators seeking differentiated strategies.",
    managersCardLabel2: "Avg. review time",
    managersCardCopy2: "Automated compliance cuts through admin drag.",
    managersBenefitsEyebrow: "Platform Benefits",
    managersBenefitsTitle: "Everything you need to scale allocator pipelines.",
    managersBenefit1Title: "Access curated allocators",
    managersBenefit1Body:
      "Targeted introductions to qualified LPs actively allocating to your strategy class.",
    managersBenefit2Title: "Secure data rooms",
    managersBenefit2Body:
      "Permissioned vaults with watermarking and activity visibility for every data room.",
    managersBenefit3Title: "Compliance workflows",
    managersBenefit3Body:
      "Built-in KYC, KYB, and governance checks keep diligence moving without bottlenecks.",
    managersBenefit4Title: "Embedded performance intelligence",
    managersBenefit4Body:
      "Automated telemetry streams performance, risk corridors, and factor drift to LPs.",
    managersOnboardingEyebrow: "Onboarding",
    managersOnboardingTitle: "Institutional distribution in four steps.",
    managersStep1: "Submit strategy profile",
    managersStep2: "Verification & compliance",
    managersStep3: "Data integration & risk mapping",
    managersStep4: "Go live to allocator marketplace",
    managersFormEyebrow: "Manager Applications",
    managersFormTitle: "Apply to distribute on IGATES.",
    managersFormLead: "Provide your strategy details and our team will coordinate diligence and onboarding.",
    managersFormResponseLabel: "Response time",
    managersFormResponseMetric: "< 48 hours",
    managersFormSecurityLabel: "Security",
    managersFormSecurityMetric: "Compliance-first",
    managersFormCoverageLabel: "Coverage",
    managersFormCoverageMetric: "Global allocators",
    familyHeroEyebrow: "Family Offices",
    familyHeroTitle: "Institutional Access for Modern Family Offices.",
    familyHeroLead: "Simplify manager discovery, diligence, and allocation workflows.",
    familyHeroCta: "Request Access",
    familyHeroTrust1: "Allocator-grade reporting",
    familyHeroTrust2: "Private data workflows",
    familyCardLabel1: "Strategies reviewed",
    familyCardCopy1: "Cross-asset intelligence tailored to mandate criteria.",
    familyCardLabel2: "Diligence files",
    familyCardMetric2: "Secure",
    familyCardCopy2: "Audit-ready archives with automated updates.",
    familyWhyEyebrow: "Why IGATES",
    familyWhyTitle: "Operational clarity for investment principals.",
    familyWhy1Title: "Verified data streams",
    familyWhy1Body: "Custodian, admin, and auditor-aligned reporting you can trust.",
    familyWhy2Title: "Audit-ready reporting",
    familyWhy2Body: "IC-ready packages with complete attribution and variance breakdowns.",
    familyWhy3Title: "Consolidated manager reviews",
    familyWhy3Body: "Side-by-side diligence trackers, notes, and signals in one workspace.",
    familyWhy4Title: "Risk corridor analytics",
    familyWhy4Body: "Scenario-aware bands so allocations stay inside mandate corridors.",
    familyCuratedEyebrow: "Curated Mandates",
    familyCuratedTitle: "Allocator-first views into leading strategies.",
    familyMandate1: "Macro",
    familyMandate1Body: "Global macro managers with disciplined risk corridors.",
    familyMandate2: "Credit",
    familyMandate2Body: "Event-driven and structured credit insights with live exposure checks.",
    familyMandate3: "Digital Assets",
    familyMandate3Body: "On-chain transparency with institutional-grade custody signals.",
    familyMandate4: "Systematic Strategies",
    familyMandate4Body: "Factor-aware systems with monitored model drift and capacity.",
    familyFormEyebrow: "Access Requests",
    familyFormTitle: "Request allocator access.",
    familyFormLead: "Tell us about your mandate, and we will provision secure access to managers.",
    familyFormResponseLabel: "Response time",
    familyFormResponseMetric: "< 24 hours",
    familyFormSecurityLabel: "Security",
    familyFormSecurityMetric: "Compliance-first",
    familyFormCoverageLabel: "Coverage",
    familyFormCoverageMetric: "Global managers",
  },
  es: {
    languageSelectLabel: "Seleccionar idioma",
    languageOptionsLabel: "Opciones de idioma",
    brandAriaLabel: "Inicio de IGATES",
    brandAlt: "Logo de IGATES Fund Intelligence",
    navWhy: "Por qué IGATES",
    navVerifiedManagers: "Gestores verificados",
    navManagers: "Gestor de fondos",
    navFamily: "Family Offices",
    navLearn: "Aprender",
    navContact: "Contacto",
    navAuthSignup: "Registrarse / Iniciar sesión",
    navAuthMaster: "Panel maestro",
    navAuthManager: "Panel de gestores",
    navAuthProfile: "Mi perfil",
    heroEyebrow: "Acceso institucional",
    heroTitle: "Conectando capital con gestores verificados",
    heroLead: "Infraestructura institucional para acceder a fondos gestionados con estándares profesionales.",
    heroCtaInvestor: "Solicitar acceso institucional",
    heroCtaManager: "Postularse como gestor",
    heroTrust1: "Operamos con entidades reguladas",
    heroTrust2: "Cuentas segregadas y fondos protegidos",
    heroTrust3: "Reporting mensual verificado",
    heroPerformanceLabel: "Rendimiento YTD",
    heroVolatilityLabel: "Volatilidad",
    heroMaxDrawdownLabel: "Máx. caída",
    heroRiskLabel: "Riesgo",
    heroRiskLevel: "Medio-Bajo",
    heroAumLabel: "AUM verificado",
    heroManagersLabel: "Con 10 gestores",
    heroMetricsLabel: "Métricas consolidadas",
    heroMetricsCta: "Ver estadísticas completas",
    whyEyebrow: "Propósito estratégico",
    whyTitle: "¿Por qué existe IGATES?",
    whyLead: "Un puente curado entre capital calificado y gestores privados con historial verificado.",
    whyCard1Title: "Cuentas auditadas y capital verificado",
    whyCard1Body:
      "Trabajamos exclusivamente con fondos que cuentan con más de 12 meses de historial auditado, operando capital real bajo custodios y entidades reguladas.",
    whyCard1Spec: "VERIFICACIÓN",
    whyCard1Alt: "Gráfico de verificación de track record",
    whyCard2Title: "Acompañamiento continuo y control de riesgo",
    whyCard2Body:
      "Soporte activo durante el onboarding y a lo largo del ciclo de inversión. Entregamos reportes mensuales y realizamos ajustes de nivel de riesgo en consenso entre inversionistas y gestores privados.",
    whyCard2Spec: "CONTROL DE RIESGO",
    whyCard2Alt: "Gráfico de soporte continuo y control de riesgo",
    whyCard3Title: "Infraestructura de ejecución",
    whyCard3Body:
      "Arquitectura operativa preparada para integraciones broker-grade, con flujos de ejecución y liquidez coordinados bajo estándares institucionales.",
    whyCard3Spec: "EJECUCIÓN",
    whyCard3Alt: "Gráfico de gestores globales y estrategias diversificadas",
    whyFooterNote:
      "IGATES es la capa de verificación y reporting; la ejecución y custodia ocurren vía brokers integrados.",
    learnEyebrow: "Foro diario",
    learnTitle: "Aprendizaje y comunidad",
    learnLead: "Briefings y highlights para mantenerte informado cada día.",
    learnPost1Title: "Radar de asignación: crédito y macro tendencias",
    learnPost1Time: "Hoy",
    learnPost1Body:
      "Hilos destacados con allocators sobre liquidez multi-activo, riesgo de duración y coberturas macro.",
    learnPost2Title: "Manager spotlight: neutralidad en activos digitales",
    learnPost2Time: "Actualizado a diario",
    learnPost2Body:
      "Resumen diario de notas de riesgo y updates operativos del desk de activos digitales.",
    learnPost3Title: "Community brief: operaciones y compliance",
    learnPost3Time: "Esta semana",
    learnPost3Body: "Q&A sobre checklists de onboarding, data rooms y preparación para auditorías.",
    complianceEyebrow: "Compliance primero",
    complianceTitle: "Controles de grado regulatorio en cada etapa.",
    complianceBody:
      "Infraestructura lista para SOC2, residencia de datos geocercada y permisos por capas mantienen la información sensible protegida.",
    complianceIdentityTitle: "Identidad y acceso",
    complianceIdentityBody: "Autenticación multifactor, SSO/SAML y bóvedas seguras para documentos y NDAs.",
    complianceMonitoringTitle: "Monitoreo",
    complianceMonitoringBody:
      "Trazas de auditoría automatizadas, alertas por umbral y cifrado en tránsito y en reposo.",
    complianceGovernanceTitle: "Gobernanza",
    complianceGovernanceBody: "Políticas preconfiguradas alineadas a estándares institucionales de due diligence.",
    contactEyebrow: "Conversemos",
    contactTitle: "Inicia tu proceso de acceso.",
    contactLead:
      "Cuéntanos sobre tu mandato o estrategia. Nuestro equipo coordinará data rooms, solicitudes de due diligence y acceso seguro.",
    contactResponseLabel: "Tiempo de respuesta",
    contactResponseMetric: "< 24 horas",
    contactCoverageLabel: "Cobertura",
    contactCoverageMetric: "Allocators globales",
    contactSecurityLabel: "Seguridad",
    contactSecurityMetric: "Listo para SOC2",
    contactNameLabel: "Nombre",
    contactNamePlaceholder: "Tu nombre completo",
    contactEmailLabel: "Email",
    contactEmailPlaceholder: "tucorreo@firma.com",
    contactRoleLabel: "Rol",
    contactRoleAria: "Rol",
    contactRolePlaceholder: "Selecciona tu rol",
    contactRoleAllocator: "Allocator / Inversionista",
    contactRoleManager: "Gestor de fondos",
    contactRoleOps: "Operaciones / Compliance",
    contactNotesLabel: "Notas",
    contactNotesPlaceholder: "Tamaño del mandato, estrategias, timing",
    contactSubmit: "Solicitar asesoría",
    contactStatusSending: "Enviando...",
    contactStatusSuccess: "Recibimos tu solicitud. Nuestro equipo responderá pronto.",
    contactStatusError: "No se pudo enviar. Confirma que el backend esté activo.",
    formNameLabel: "Nombre",
    formNamePlaceholder: "Tu nombre completo",
    formFirmLabel: "Firma",
    formFirmPlaceholderFamily: "Nombre del family office",
    formFirmPlaceholderManager: "Nombre de la firma",
    formStrategyLabel: "Tipo de estrategia",
    formStrategyPlaceholderFamily: "Macro, Crédito, Activos digitales...",
    formStrategyPlaceholderManager: "Crédito, Macro, Activos digitales...",
    formAumLabel: "AUM",
    formAumPlaceholderFamily: "$500M",
    formAumPlaceholderManager: "$250M",
    formEmailLabel: "Email",
    formEmailPlaceholderFamily: "tu@office.com",
    formEmailPlaceholderManager: "tu@firma.com",
    formNotesLabel: "Notas",
    formNotesPlaceholderFamily: "Tamaño del mandato, estrategias objetivo, plazos",
    formNotesPlaceholderManager: "Foco del mandato, plazos, objetivos",
    familyFormSubmit: "Solicitar acceso",
    formSubmit: "Postularse como gestor",
    formStatusSending: "Enviando...",
    formStatusSuccess: "Enviado.",
    formStatusError: "No se pudo enviar en este momento.",
    fundsLoading: "Cargando fondos verificados...",
    fundsLoadError: "No se pudieron cargar los fondos. Inicia el backend.",
    fundsEmpty: "No hay fondos verificados disponibles.",
    fundsStatusVerified: "Verificado",
    fundsSummaryDefault: "Gestor en proceso de verificación.",
    fundsHighlight1: "Track record verificado",
    fundsHighlight2: "Reporting mensual",
    fundsHighlight3: "Due diligence listo",
    fundsLabelAum: "AUM",
    fundsLabelYtd: "YTD",
    fundsLabelRisk: "Riesgo",
    fundsLabelStrategyFallback: "Multi-estrategia",
    fundsLabelDomicileFallback: "Global",
    insightsLoading: "Cargando inteligencia...",
    insightsLoadError: "No se pudieron cargar los insights. Inicia el backend.",
    footerTagline: "Conectividad elite para gestores de fondos y capital calificado.",
    footerPlatform: "Plataforma",
    footerOverview: "Resumen",
    footerFeaturedFunds: "Fondos destacados",
    footerIntelligence: "Inteligencia",
    footerCompany: "Compañía",
    footerAbout: "Nosotros",
    footerCompliance: "Compliance",
    footerCareers: "Carreras",
    footerContact: "Contacto",
    footerRequestCall: "Solicitar una llamada",
    footerInvestorRelations: "Relación con inversionistas",
    footerRights: "© 2024 IGATES. Todos los derechos reservados.",
    footerPrivacy: "Privacidad y seguridad",
    managersHeroEyebrow: "Para gestores",
    managersHeroTitle: "Distribución diseñada para estrategias élite.",
    managersHeroLead:
      "Conecta con allocators globales verificados usando la infraestructura institucional de IGATES.",
    managersHeroCta: "Postularse como gestor",
    managersHeroTrust1: "Cobertura de allocators en macro, crédito y activos digitales",
    managersHeroTrust2: "Intercambio de datos listo para SOC2",
    managersCardLabel1: "Mandatos activos",
    managersCardCopy1: "Allocators calificados buscando estrategias diferenciadas.",
    managersCardLabel2: "Tiempo medio de revisión",
    managersCardCopy2: "Compliance automatizado elimina fricción administrativa.",
    managersBenefitsEyebrow: "Beneficios de la plataforma",
    managersBenefitsTitle: "Todo lo que necesitas para escalar pipelines de allocators.",
    managersBenefit1Title: "Acceso a allocators curados",
    managersBenefit1Body:
      "Introducciones dirigidas a LPs calificados que asignan activamente a tu clase de estrategia.",
    managersBenefit2Title: "Data rooms seguros",
    managersBenefit2Body:
      "Bóvedas con permisos, marcas de agua y visibilidad de actividad para cada data room.",
    managersBenefit3Title: "Flujos de compliance",
    managersBenefit3Body:
      "KYC, KYB y controles de gobernanza integrados mantienen la diligencia sin cuellos de botella.",
    managersBenefit4Title: "Inteligencia de performance embebida",
    managersBenefit4Body:
      "Telemetría automatizada transmite performance, corredores de riesgo y deriva de factores a los LPs.",
    managersOnboardingEyebrow: "Onboarding",
    managersOnboardingTitle: "Distribución institucional en cuatro pasos.",
    managersStep1: "Enviar perfil de estrategia",
    managersStep2: "Verificación y compliance",
    managersStep3: "Integración de datos y mapeo de riesgo",
    managersStep4: "Publicación en marketplace de allocators",
    managersFormEyebrow: "Aplicaciones de gestores",
    managersFormTitle: "Postula para distribuir en IGATES.",
    managersFormLead:
      "Entrega los detalles de tu estrategia y nuestro equipo coordinará la diligencia y el onboarding.",
    managersFormResponseLabel: "Tiempo de respuesta",
    managersFormResponseMetric: "< 48 horas",
    managersFormSecurityLabel: "Seguridad",
    managersFormSecurityMetric: "Compliance primero",
    managersFormCoverageLabel: "Cobertura",
    managersFormCoverageMetric: "Allocators globales",
    familyHeroEyebrow: "Family Offices",
    familyHeroTitle: "Acceso institucional para family offices modernos.",
    familyHeroLead: "Simplifica el descubrimiento, la diligencia y la asignación con gestores.",
    familyHeroCta: "Solicitar acceso",
    familyHeroTrust1: "Reporting de nivel allocator",
    familyHeroTrust2: "Flujos de datos privados",
    familyCardLabel1: "Estrategias revisadas",
    familyCardCopy1: "Inteligencia cross-asset ajustada a criterios del mandato.",
    familyCardLabel2: "Archivos de diligencia",
    familyCardMetric2: "Seguro",
    familyCardCopy2: "Archivos listos para auditoría con actualizaciones automáticas.",
    familyWhyEyebrow: "Por qué IGATES",
    familyWhyTitle: "Claridad operativa para responsables de inversión.",
    familyWhy1Title: "Flujos de datos verificados",
    familyWhy1Body:
      "Reporting alineado con custodios, administradores y auditores en el que puedes confiar.",
    familyWhy2Title: "Reporting listo para auditoría",
    familyWhy2Body: "Paquetes listos para comité con atribución completa y desgloses de variación.",
    familyWhy3Title: "Revisiones consolidadas de gestores",
    familyWhy3Body: "Seguimiento de diligencia, notas y señales lado a lado en un solo espacio.",
    familyWhy4Title: "Analítica de corredores de riesgo",
    familyWhy4Body: "Bandas conscientes de escenarios para mantener asignaciones dentro del mandato.",
    familyCuratedEyebrow: "Mandatos curados",
    familyCuratedTitle: "Vistas centradas en allocators de estrategias líderes.",
    familyMandate1: "Macro",
    familyMandate1Body: "Gestores macro globales con corredores de riesgo disciplinados.",
    familyMandate2: "Crédito",
    familyMandate2Body: "Insights de crédito estructurado y event-driven con chequeos de exposición en vivo.",
    familyMandate3: "Activos digitales",
    familyMandate3Body: "Transparencia on-chain con señales de custodia de grado institucional.",
    familyMandate4: "Estrategias sistemáticas",
    familyMandate4Body: "Sistemas conscientes de factores con deriva de modelos y capacidad monitoreadas.",
    familyFormEyebrow: "Solicitudes de acceso",
    familyFormTitle: "Solicita acceso como allocator.",
    familyFormLead: "Cuéntanos sobre tu mandato y habilitaremos acceso seguro a gestores.",
    familyFormResponseLabel: "Tiempo de respuesta",
    familyFormResponseMetric: "< 24 horas",
    familyFormSecurityLabel: "Seguridad",
    familyFormSecurityMetric: "Compliance primero",
    familyFormCoverageLabel: "Cobertura",
    familyFormCoverageMetric: "Gestores globales",
  },
  pt: {
    languageSelectLabel: "Selecionar idioma",
    languageOptionsLabel: "Opções de idioma",
    brandAriaLabel: "Página inicial da IGATES",
    brandAlt: "Logotipo IGATES Fund Intelligence",
    navWhy: "Por que IGATES",
    navVerifiedManagers: "Gestores verificados",
    navManagers: "Gestor de fundos",
    navFamily: "Family Offices",
    navLearn: "Aprender",
    navContact: "Contato",
    navAuthSignup: "Cadastrar / Entrar",
    navAuthMaster: "Painel master",
    navAuthManager: "Painel do gestor",
    navAuthProfile: "Meu perfil",
    heroEyebrow: "Acesso institucional",
    heroTitle: "Conectando capital a gestores verificados",
    heroLead: "Infraestrutura institucional para acessar fundos geridos com padrões profissionais.",
    heroCtaInvestor: "Solicitar acesso institucional",
    heroCtaManager: "Candidatar-se como gestor",
    heroTrust1: "Operação com entidades reguladas",
    heroTrust2: "Contas segregadas e fundos protegidos",
    heroTrust3: "Relatórios mensais verificados",
    heroPerformanceLabel: "Performance YTD",
    heroVolatilityLabel: "Volatilidade",
    heroMaxDrawdownLabel: "Queda máxima",
    heroRiskLabel: "Risco",
    heroRiskLevel: "Médio-Baixo",
    heroAumLabel: "AUM verificado",
    heroManagersLabel: "Com 10 gestores",
    heroMetricsLabel: "Métricas consolidadas",
    heroMetricsCta: "Ver estatísticas completas",
    whyEyebrow: "Propósito estratégico",
    whyTitle: "Por que a IGATES existe?",
    whyLead: "Uma ponte curada entre capital qualificado e gestores privados com histórico verificado.",
    whyCard1Title: "Contas auditadas e capital verificado",
    whyCard1Body:
      "Trabalhamos exclusivamente com fundos que possuem mais de 12 meses de histórico auditado, operando capital real com custodiante e entidades reguladas.",
    whyCard1Spec: "VERIFICAÇÃO",
    whyCard1Alt: "Gráfico de verificação do track record",
    whyCard2Title: "Suporte contínuo e controle de risco",
    whyCard2Body:
      "Suporte ativo durante o onboarding e ao longo do ciclo de investimento. Entregamos relatórios mensais e ajustamos níveis de risco em consenso entre investidores e gestores privados.",
    whyCard2Spec: "SUPERVISÃO DE RISCO",
    whyCard2Alt: "Gráfico de suporte contínuo e controle de risco",
    whyCard3Title: "Infraestrutura de execução",
    whyCard3Body:
      "Arquitetura operacional pronta para integrações broker-grade, com fluxos de execução e liquidez coordenados sob padrões institucionais.",
    whyCard3Spec: "EXECUÇÃO",
    whyCard3Alt: "Gráfico de gestores globais e estratégias diversificadas",
    whyFooterNote:
      "A IGATES é a camada de verificação e reporting; a execução e custódia ocorrem via brokers integrados.",
    learnEyebrow: "Fórum diário",
    learnTitle: "Aprendizado e comunidade",
    learnLead: "Briefings e destaques para mantê-lo informado todos os dias.",
    learnPost1Title: "Radar de alocação: crédito e tendências macro",
    learnPost1Time: "Hoje",
    learnPost1Body:
      "Conversas em destaque com allocators sobre liquidez multiativos, risco de duration e hedges macro.",
    learnPost2Title: "Manager spotlight: neutralidade em ativos digitais",
    learnPost2Time: "Atualizado diariamente",
    learnPost2Body:
      "Resumo diário de notas de risco e atualizações operacionais da mesa de ativos digitais.",
    learnPost3Title: "Community brief: operações e compliance",
    learnPost3Time: "Esta semana",
    learnPost3Body: "Q&A sobre checklists de onboarding, data rooms e preparação para auditorias.",
    complianceEyebrow: "Compliance primeiro",
    complianceTitle: "Controles de nível regulatório em cada etapa.",
    complianceBody:
      "Infraestrutura pronta para SOC2, residência de dados com geocercas e permissões em camadas mantêm as informações sensíveis protegidas.",
    complianceIdentityTitle: "Identidade e acesso",
    complianceIdentityBody: "Autenticação multifator, SSO/SAML e cofres seguros para documentos e NDAs.",
    complianceMonitoringTitle: "Monitoramento",
    complianceMonitoringBody:
      "Trilhas de auditoria automatizadas, alertas por limiar e criptografia em trânsito e em repouso.",
    complianceGovernanceTitle: "Governança",
    complianceGovernanceBody: "Políticas pré-configuradas alinhadas aos padrões institucionais de due diligence.",
    contactEyebrow: "Vamos conversar",
    contactTitle: "Inicie seu processo de acesso.",
    contactLead:
      "Conte-nos sobre seu mandato ou estratégia. Nossa equipe coordenará data rooms, solicitações de due diligence e acesso seguro.",
    contactResponseLabel: "Tempo de resposta",
    contactResponseMetric: "< 24 horas",
    contactCoverageLabel: "Cobertura",
    contactCoverageMetric: "Allocators globais",
    contactSecurityLabel: "Segurança",
    contactSecurityMetric: "Pronto para SOC2",
    contactNameLabel: "Nome",
    contactNamePlaceholder: "Seu nome completo",
    contactEmailLabel: "Email",
    contactEmailPlaceholder: "voce@empresa.com",
    contactRoleLabel: "Cargo",
    contactRoleAria: "Cargo",
    contactRolePlaceholder: "Selecione seu cargo",
    contactRoleAllocator: "Allocator / Investidor",
    contactRoleManager: "Gestor de fundos",
    contactRoleOps: "Operações / Compliance",
    contactNotesLabel: "Observações",
    contactNotesPlaceholder: "Tamanho do mandato, estratégias, prazos",
    contactSubmit: "Solicitar assessoria",
    contactStatusSending: "Enviando...",
    contactStatusSuccess: "Recebemos sua solicitação. Nossa equipe responderá em breve.",
    contactStatusError: "Não foi possível enviar agora. Confirme se o backend está ativo.",
    formNameLabel: "Nome",
    formNamePlaceholder: "Seu nome completo",
    formFirmLabel: "Empresa",
    formFirmPlaceholderFamily: "Nome do family office",
    formFirmPlaceholderManager: "Nome da empresa",
    formStrategyLabel: "Tipo de estratégia",
    formStrategyPlaceholderFamily: "Macro, Crédito, Ativos digitais...",
    formStrategyPlaceholderManager: "Crédito, Macro, Ativos digitais...",
    formAumLabel: "AUM",
    formAumPlaceholderFamily: "$500M",
    formAumPlaceholderManager: "$250M",
    formEmailLabel: "Email",
    formEmailPlaceholderFamily: "voce@office.com",
    formEmailPlaceholderManager: "voce@empresa.com",
    formNotesLabel: "Observações",
    formNotesPlaceholderFamily: "Tamanho do mandato, estratégias-alvo, prazos",
    formNotesPlaceholderManager: "Foco do mandato, prazos, metas",
    familyFormSubmit: "Solicitar acesso",
    formSubmit: "Candidatar-se como gestor",
    formStatusSending: "Enviando...",
    formStatusSuccess: "Enviado!",
    formStatusError: "Não foi possível enviar agora.",
    fundsLoading: "Carregando fundos verificados...",
    fundsLoadError: "Não foi possível carregar os fundos. Inicie o backend.",
    fundsEmpty: "Nenhum fundo verificado disponível.",
    fundsStatusVerified: "Verificado",
    fundsSummaryDefault: "Gestor em processo de verificação.",
    fundsHighlight1: "Track record verificado",
    fundsHighlight2: "Relatórios mensais",
    fundsHighlight3: "Due diligence pronta",
    fundsLabelAum: "AUM",
    fundsLabelYtd: "YTD",
    fundsLabelRisk: "Risco",
    fundsLabelStrategyFallback: "Multi-estratégia",
    fundsLabelDomicileFallback: "Global",
    insightsLoading: "Carregando insights...",
    insightsLoadError: "Não foi possível carregar os insights. Inicie o backend.",
    footerTagline: "Conectividade de elite para gestores de fundos e capital qualificado.",
    footerPlatform: "Plataforma",
    footerOverview: "Visão geral",
    footerFeaturedFunds: "Fundos em destaque",
    footerIntelligence: "Inteligência",
    footerCompany: "Empresa",
    footerAbout: "Sobre",
    footerCompliance: "Compliance",
    footerCareers: "Carreiras",
    footerContact: "Contato",
    footerRequestCall: "Solicitar uma ligação",
    footerInvestorRelations: "Relações com investidores",
    footerRights: "© 2024 IGATES. Todos os direitos reservados.",
    footerPrivacy: "Privacidade e segurança",
    managersHeroEyebrow: "Para gestores",
    managersHeroTitle: "Distribuição feita para estratégias de elite.",
    managersHeroLead:
      "Conecte-se a allocators globais verificados com a infraestrutura institucional da IGATES.",
    managersHeroCta: "Candidatar-se como gestor",
    managersHeroTrust1: "Cobertura de allocators em macro, crédito e ativos digitais",
    managersHeroTrust2: "Troca de dados pronta para SOC2",
    managersCardLabel1: "Mandatos ativos",
    managersCardCopy1: "Allocators qualificados buscando estratégias diferenciadas.",
    managersCardLabel2: "Tempo médio de revisão",
    managersCardCopy2: "Compliance automatizado reduz a burocracia.",
    managersBenefitsEyebrow: "Benefícios da plataforma",
    managersBenefitsTitle: "Tudo o que você precisa para escalar pipelines de allocators.",
    managersBenefit1Title: "Acesso a allocators curados",
    managersBenefit1Body:
      "Introduções direcionadas a LPs qualificados que alocam ativamente na sua classe de estratégia.",
    managersBenefit2Title: "Data rooms seguros",
    managersBenefit2Body:
      "Cofres com permissões, marca d'água e visibilidade de atividade para cada data room.",
    managersBenefit3Title: "Fluxos de compliance",
    managersBenefit3Body:
      "KYC, KYB e checagens de governança integradas mantêm a diligência em movimento sem gargalos.",
    managersBenefit4Title: "Inteligência de performance integrada",
    managersBenefit4Body:
      "Telemetria automatizada envia performance, corredores de risco e deriva de fatores aos LPs.",
    managersOnboardingEyebrow: "Onboarding",
    managersOnboardingTitle: "Distribuição institucional em quatro etapas.",
    managersStep1: "Enviar perfil de estratégia",
    managersStep2: "Verificação e compliance",
    managersStep3: "Integração de dados e mapeamento de risco",
    managersStep4: "Entrar no marketplace de allocators",
    managersFormEyebrow: "Aplicações de gestores",
    managersFormTitle: "Candidate-se para distribuir na IGATES.",
    managersFormLead:
      "Forneça os detalhes da sua estratégia e nossa equipe coordenará a diligência e o onboarding.",
    managersFormResponseLabel: "Tempo de resposta",
    managersFormResponseMetric: "< 48 horas",
    managersFormSecurityLabel: "Segurança",
    managersFormSecurityMetric: "Compliance em primeiro lugar",
    managersFormCoverageLabel: "Cobertura",
    managersFormCoverageMetric: "Allocators globais",
    familyHeroEyebrow: "Family Offices",
    familyHeroTitle: "Acesso institucional para family offices modernos.",
    familyHeroLead: "Simplifique a descoberta, diligência e alocação de gestores.",
    familyHeroCta: "Solicitar acesso",
    familyHeroTrust1: "Relatórios de nível allocator",
    familyHeroTrust2: "Fluxos de dados privados",
    familyCardLabel1: "Estratégias revisadas",
    familyCardCopy1: "Inteligência cross-asset ajustada aos critérios do mandato.",
    familyCardLabel2: "Arquivos de diligência",
    familyCardMetric2: "Seguro",
    familyCardCopy2: "Arquivos prontos para auditoria com atualizações automatizadas.",
    familyWhyEyebrow: "Por que IGATES",
    familyWhyTitle: "Clareza operacional para responsáveis de investimento.",
    familyWhy1Title: "Fluxos de dados verificados",
    familyWhy1Body: "Relatórios alinhados com custodiante, admin e auditor em que você pode confiar.",
    familyWhy2Title: "Relatórios prontos para auditoria",
    familyWhy2Body: "Pacotes prontos para o comitê com atribuição completa e detalhamento de variações.",
    familyWhy3Title: "Revisões consolidadas de gestores",
    familyWhy3Body: "Rastreadores de diligência, notas e sinais lado a lado em um único espaço.",
    familyWhy4Title: "Análises de corredores de risco",
    familyWhy4Body: "Bandas sensíveis a cenários para manter alocações dentro dos corredores do mandato.",
    familyCuratedEyebrow: "Mandatos curados",
    familyCuratedTitle: "Visões focadas no allocator para estratégias líderes.",
    familyMandate1: "Macro",
    familyMandate1Body: "Gestores macro globais com corredores de risco disciplinados.",
    familyMandate2: "Crédito",
    familyMandate2Body: "Insights de crédito estruturado e event-driven com checagens de exposição em tempo real.",
    familyMandate3: "Ativos digitais",
    familyMandate3Body: "Transparência on-chain com sinais de custódia de nível institucional.",
    familyMandate4: "Estratégias sistemáticas",
    familyMandate4Body: "Sistemas conscientes de fatores com deriva de modelos e capacidade monitoradas.",
    familyFormEyebrow: "Solicitações de acesso",
    familyFormTitle: "Solicitar acesso como allocator.",
    familyFormLead: "Conte-nos sobre seu mandato e forneceremos acesso seguro a gestores.",
    familyFormResponseLabel: "Tempo de resposta",
    familyFormResponseMetric: "< 24 horas",
    familyFormSecurityLabel: "Segurança",
    familyFormSecurityMetric: "Compliance em primeiro lugar",
    familyFormCoverageLabel: "Cobertura",
    familyFormCoverageMetric: "Gestores globais",
  },
  it: {
    languageSelectLabel: "Seleziona lingua",
    languageOptionsLabel: "Opzioni lingua",
    brandAriaLabel: "Home IGATES",
    brandAlt: "Logo IGATES Fund Intelligence",
    navWhy: "Perché IGATES",
    navVerifiedManagers: "Gestori verificati",
    navManagers: "Fund manager",
    navFamily: "Family office",
    navLearn: "Approfondimenti",
    navContact: "Contatto",
    navAuthSignup: "Registrati / Accedi",
    navAuthMaster: "Dashboard master",
    navAuthManager: "Dashboard gestore",
    navAuthProfile: "Il mio profilo",
    heroEyebrow: "Accesso istituzionale",
    heroTitle: "Connettiamo capitale con gestori verificati",
    heroLead: "Infrastruttura istituzionale per accedere a fondi gestiti con standard professionali.",
    heroCtaInvestor: "Richiedi accesso istituzionale",
    heroCtaManager: "Candidati come gestore",
    heroTrust1: "Operiamo con entità regolamentate",
    heroTrust2: "Conti segregati e fondi protetti",
    heroTrust3: "Reporting mensile verificato",
    heroPerformanceLabel: "Performance YTD",
    heroVolatilityLabel: "Volatilità",
    heroMaxDrawdownLabel: "Drawdown massimo",
    heroRiskLabel: "Rischio",
    heroRiskLevel: "Medio-basso",
    heroAumLabel: "AUM verificato",
    heroManagersLabel: "Con 10 gestori",
    heroMetricsLabel: "Metriche consolidate",
    heroMetricsCta: "Vedi statistiche complete",
    whyEyebrow: "Scopo strategico",
    whyTitle: "Perché esiste IGATES?",
    whyLead: "Un ponte curato tra capitale qualificato e gestori privati con track record verificato.",
    whyCard1Title: "Conti auditati e capitale verificato",
    whyCard1Body:
      "Lavoriamo esclusivamente con fondi che hanno oltre 12 mesi di storico auditato, operando capitale reale con custodi ed entità regolamentate.",
    whyCard1Spec: "VERIFICA",
    whyCard1Alt: "Grafica di verifica del track record",
    whyCard2Title: "Supporto continuo e controllo del rischio",
    whyCard2Body:
      "Supporto attivo durante l'onboarding e lungo il ciclo d'investimento. Forniamo report mensili e adeguiamo i livelli di rischio in accordo tra investitori e gestori privati.",
    whyCard2Spec: "SUPERVISIONE RISCHIO",
    whyCard2Alt: "Grafica di supporto continuo e controllo del rischio",
    whyCard3Title: "Infrastruttura di esecuzione",
    whyCard3Body:
      "Architettura operativa pronta per integrazioni broker-grade, con flussi di esecuzione e liquidità coordinati secondo standard istituzionali.",
    whyCard3Spec: "ESECUZIONE",
    whyCard3Alt: "Grafica su gestori globali e strategie diversificate",
    whyFooterNote:
      "IGATES è il livello di verifica e reporting; esecuzione e custodia avvengono tramite broker integrati.",
    learnEyebrow: "Forum quotidiano",
    learnTitle: "Formazione e community",
    learnLead: "Briefing e highlight per restare informato ogni giorno.",
    learnPost1Title: "Radar allocazioni: credito e trend macro",
    learnPost1Time: "Oggi",
    learnPost1Body:
      "Thread in evidenza con allocators su liquidità multi-asset, rischio di duration e coperture macro.",
    learnPost2Title: "Manager spotlight: neutralità su asset digitali",
    learnPost2Time: "Aggiornato quotidianamente",
    learnPost2Body:
      "Sintesi giornaliera di note di rischio e aggiornamenti operativi dal desk di asset digitali.",
    learnPost3Title: "Community brief: operazioni e compliance",
    learnPost3Time: "Questa settimana",
    learnPost3Body: "Q&A su checklist di onboarding, data room e preparazione alle audit.",
    complianceEyebrow: "Compliance first",
    complianceTitle: "Controlli di livello regolatorio in ogni fase.",
    complianceBody:
      "Infrastruttura pronta per SOC2, data residency georeferenziata e permessi a livelli mantengono protette le informazioni sensibili.",
    complianceIdentityTitle: "Identità e accesso",
    complianceIdentityBody: "Autenticazione multifattore, SSO/SAML e vault sicuri per documenti e NDA.",
    complianceMonitoringTitle: "Monitoraggio",
    complianceMonitoringBody: "Audit trail automatizzati, alert per soglia e cifratura in transito e a riposo.",
    complianceGovernanceTitle: "Governance",
    complianceGovernanceBody: "Policy preconfigurate allineate agli standard istituzionali di due diligence.",
    contactEyebrow: "Parliamone",
    contactTitle: "Avvia il tuo processo di accesso.",
    contactLead:
      "Raccontaci il tuo mandato o strategia. Il nostro team coordinerà data room, richieste di due diligence e accesso sicuro.",
    contactResponseLabel: "Tempo di risposta",
    contactResponseMetric: "< 24 ore",
    contactCoverageLabel: "Copertura",
    contactCoverageMetric: "Allocators globali",
    contactSecurityLabel: "Sicurezza",
    contactSecurityMetric: "Pronto per SOC2",
    contactNameLabel: "Nome",
    contactNamePlaceholder: "Il tuo nome completo",
    contactEmailLabel: "Email",
    contactEmailPlaceholder: "tuo@azienda.com",
    contactRoleLabel: "Ruolo",
    contactRoleAria: "Ruolo",
    contactRolePlaceholder: "Seleziona il tuo ruolo",
    contactRoleAllocator: "Allocator / Investitore",
    contactRoleManager: "Fund manager",
    contactRoleOps: "Operazioni / Compliance",
    contactNotesLabel: "Note",
    contactNotesPlaceholder: "Dimensione mandato, strategie, tempistiche",
    contactSubmit: "Richiedi consulenza",
    contactStatusSending: "Invio in corso...",
    contactStatusSuccess: "Abbiamo ricevuto la tua richiesta. Risponderemo a breve.",
    contactStatusError: "Impossibile inviare ora. Verifica che il backend sia attivo.",
    formNameLabel: "Nome",
    formNamePlaceholder: "Il tuo nome completo",
    formFirmLabel: "Società",
    formFirmPlaceholderFamily: "Nome del family office",
    formFirmPlaceholderManager: "Nome della società",
    formStrategyLabel: "Tipo di strategia",
    formStrategyPlaceholderFamily: "Macro, Credito, Asset digitali...",
    formStrategyPlaceholderManager: "Credito, Macro, Asset digitali...",
    formAumLabel: "AUM",
    formAumPlaceholderFamily: "$500M",
    formAumPlaceholderManager: "$250M",
    formEmailLabel: "Email",
    formEmailPlaceholderFamily: "tuo@office.com",
    formEmailPlaceholderManager: "tuo@azienda.com",
    formNotesLabel: "Note",
    formNotesPlaceholderFamily: "Dimensione del mandato, strategie target, tempistiche",
    formNotesPlaceholderManager: "Focus del mandato, tempistiche, obiettivi",
    familyFormSubmit: "Richiedi accesso",
    formSubmit: "Candidati come gestore",
    formStatusSending: "Invio in corso...",
    formStatusSuccess: "Inviato!",
    formStatusError: "Impossibile inviare ora.",
    fundsLoading: "Caricamento fondi verificati...",
    fundsLoadError: "Impossibile caricare i fondi. Avvia il backend.",
    fundsEmpty: "Nessun fondo verificato disponibile.",
    fundsStatusVerified: "Verificato",
    fundsSummaryDefault: "Gestore in fase di verifica.",
    fundsHighlight1: "Track record verificato",
    fundsHighlight2: "Reporting mensile",
    fundsHighlight3: "Due diligence pronta",
    fundsLabelAum: "AUM",
    fundsLabelYtd: "YTD",
    fundsLabelRisk: "Rischio",
    fundsLabelStrategyFallback: "Multi-strategy",
    fundsLabelDomicileFallback: "Globale",
    insightsLoading: "Caricamento insight...",
    insightsLoadError: "Impossibile caricare gli insight. Avvia il backend.",
    footerTagline: "Connettività d'élite per gestori di fondi e capitale qualificato.",
    footerPlatform: "Piattaforma",
    footerOverview: "Panoramica",
    footerFeaturedFunds: "Fondi in evidenza",
    footerIntelligence: "Intelligence",
    footerCompany: "Azienda",
    footerAbout: "Chi siamo",
    footerCompliance: "Compliance",
    footerCareers: "Carriere",
    footerContact: "Contatto",
    footerRequestCall: "Richiedi una call",
    footerInvestorRelations: "Relazioni con gli investitori",
    footerRights: "© 2024 IGATES. Tutti i diritti riservati.",
    footerPrivacy: "Privacy e sicurezza",
    managersHeroEyebrow: "Per gestori",
    managersHeroTitle: "Distribuzione pensata per strategie d'élite.",
    managersHeroLead:
      "Connettiti con allocators globali verificati tramite l'infrastruttura istituzionale di IGATES.",
    managersHeroCta: "Candidati come gestore",
    managersHeroTrust1: "Copertura allocators su macro, credito, asset digitali",
    managersHeroTrust2: "Scambio dati pronto per SOC2",
    managersCardLabel1: "Mandati attivi",
    managersCardCopy1: "Allocators qualificati alla ricerca di strategie differenziate.",
    managersCardLabel2: "Tempo medio di revisione",
    managersCardCopy2: "La compliance automatizzata riduce l'attrito amministrativo.",
    managersBenefitsEyebrow: "Benefici della piattaforma",
    managersBenefitsTitle: "Tutto ciò che serve per scalare i pipeline di allocators.",
    managersBenefit1Title: "Accesso a allocators curati",
    managersBenefit1Body:
      "Introduzioni mirate a LP qualificati che allocano attivamente nella tua classe di strategia.",
    managersBenefit2Title: "Data room sicure",
    managersBenefit2Body:
      "Vault con permessi, watermarking e visibilità dell'attività per ogni data room.",
    managersBenefit3Title: "Workflow di compliance",
    managersBenefit3Body:
      "Controlli KYC, KYB e governance integrati mantengono la diligence in movimento senza colli di bottiglia.",
    managersBenefit4Title: "Intelligence sulle performance integrata",
    managersBenefit4Body:
      "Telemetria automatizzata trasmette performance, corridoi di rischio e deriva dei fattori agli LP.",
    managersOnboardingEyebrow: "Onboarding",
    managersOnboardingTitle: "Distribuzione istituzionale in quattro passaggi.",
    managersStep1: "Invia il profilo strategico",
    managersStep2: "Verifica e compliance",
    managersStep3: "Integrazione dati e mappatura rischio",
    managersStep4: "Vai live nel marketplace degli allocators",
    managersFormEyebrow: "Application dei gestori",
    managersFormTitle: "Candidati per distribuire su IGATES.",
    managersFormLead:
      "Fornisci i dettagli della tua strategia e il nostro team coordinerà la diligence e l'onboarding.",
    managersFormResponseLabel: "Tempo di risposta",
    managersFormResponseMetric: "< 48 ore",
    managersFormSecurityLabel: "Sicurezza",
    managersFormSecurityMetric: "Compliance first",
    managersFormCoverageLabel: "Copertura",
    managersFormCoverageMetric: "Allocators globali",
    familyHeroEyebrow: "Family Office",
    familyHeroTitle: "Accesso istituzionale per family office moderni.",
    familyHeroLead: "Semplifica discovery, diligence e allocazione dei gestori.",
    familyHeroCta: "Richiedi accesso",
    familyHeroTrust1: "Reporting di livello allocator",
    familyHeroTrust2: "Workflow dati privati",
    familyCardLabel1: "Strategie analizzate",
    familyCardCopy1: "Intelligence cross-asset su misura per i criteri del mandato.",
    familyCardLabel2: "Diligence file",
    familyCardMetric2: "Sicuro",
    familyCardCopy2: "Archivi pronti per audit con aggiornamenti automatizzati.",
    familyWhyEyebrow: "Perché IGATES",
    familyWhyTitle: "Chiarezza operativa per i responsabili degli investimenti.",
    familyWhy1Title: "Flussi dati verificati",
    familyWhy1Body: "Reporting allineato a custodian, admin e auditor su cui puoi contare.",
    familyWhy2Title: "Reporting pronto per audit",
    familyWhy2Body: "Pacchetti pronti per IC con attribuzione completa e dettagli delle variazioni.",
    familyWhy3Title: "Revisioni consolidate dei gestori",
    familyWhy3Body: "Tracker di diligence, note e segnali affiancati in un unico workspace.",
    familyWhy4Title: "Analisi dei corridoi di rischio",
    familyWhy4Body: "Bande sensibili agli scenari per mantenere le allocazioni entro i corridoi del mandato.",
    familyCuratedEyebrow: "Mandati curati",
    familyCuratedTitle: "Visioni focalizzate sugli allocator per strategie di punta.",
    familyMandate1: "Macro",
    familyMandate1Body: "Gestori macro globali con corridoi di rischio disciplinati.",
    familyMandate2: "Credito",
    familyMandate2Body: "Insight su credito strutturato ed event-driven con controlli di esposizione live.",
    familyMandate3: "Asset digitali",
    familyMandate3Body: "Trasparenza on-chain con segnali di custodia di livello istituzionale.",
    familyMandate4: "Strategie sistematiche",
    familyMandate4Body: "Sistemi factor-aware con deriva del modello e capacità monitorata.",
    familyFormEyebrow: "Richieste di accesso",
    familyFormTitle: "Richiedi accesso come allocator.",
    familyFormLead: "Raccontaci il tuo mandato e forniremo accesso sicuro ai gestori.",
    familyFormResponseLabel: "Tempo di risposta",
    familyFormResponseMetric: "< 24 ore",
    familyFormSecurityLabel: "Sicurezza",
    familyFormSecurityMetric: "Compliance first",
    familyFormCoverageLabel: "Copertura",
    familyFormCoverageMetric: "Gestori globali",
  },
  zh: {
    languageSelectLabel: "选择语言",
    languageOptionsLabel: "语言选项",
    brandAriaLabel: "IGATES 主页",
    brandAlt: "IGATES 基金情报标志",
    navWhy: "为什么选择 IGATES",
    navVerifiedManagers: "已验证管理人",
    navManagers: "基金管理人",
    navFamily: "家族办公室",
    navLearn: "学习",
    navContact: "联系",
    navAuthSignup: "注册 / 登录",
    navAuthMaster: "主控面板",
    navAuthManager: "管理人面板",
    navAuthProfile: "我的资料",
    heroEyebrow: "机构级访问",
    heroTitle: "连接资本与已验证管理人",
    heroLead: "以机构级基础设施访问专业标准的管理型基金。",
    heroCtaInvestor: "申请机构访问",
    heroCtaManager: "申请成为管理人",
    heroTrust1: "与受监管机构合作",
    heroTrust2: "隔离账户与资金保护",
    heroTrust3: "每月报告已验证",
    heroPerformanceLabel: "YTD 表现",
    heroVolatilityLabel: "波动率",
    heroMaxDrawdownLabel: "最大回撤",
    heroRiskLabel: "风险",
    heroRiskLevel: "中低",
    heroAumLabel: "已验证 AUM",
    heroManagersLabel: "覆盖 10 位管理人",
    heroMetricsLabel: "汇总指标",
    heroMetricsCta: "查看完整统计",
    whyEyebrow: "战略使命",
    whyTitle: "IGATES 为什么存在？",
    whyLead: "在合格资本与具备可验证业绩的私募管理人之间搭建精选桥梁。",
    whyCard1Title: "审计账户与已验证资本",
    whyCard1Body:
      "我们只与拥有超过 12 个月审计记录的基金合作，在托管与受监管机构下运作真实资金。",
    whyCard1Spec: "验证",
    whyCard1Alt: "业绩记录验证图示",
    whyCard2Title: "持续支持与风险控制",
    whyCard2Body:
      "在入驻与投资周期中提供主动支持。我们提供月度报告，并与投资人和私募管理人协商调整风险水平。",
    whyCard2Spec: "风险监督",
    whyCard2Alt: "持续支持与风险控制图示",
    whyCard3Title: "执行基础设施",
    whyCard3Body:
      "面向券商级集成的运营架构，执行与流动性流程遵循机构标准。",
    whyCard3Spec: "执行通道",
    whyCard3Alt: "全球管理人与多元化策略图示",
    whyFooterNote: "IGATES 是验证与报告层；执行与托管通过集成券商完成。",
    learnEyebrow: "每日论坛",
    learnTitle: "学习与社区",
    learnLead: "每日简报与要点，助你及时掌握信息。",
    learnPost1Title: "配置雷达：信用与宏观趋势",
    learnPost1Time: "今天",
    learnPost1Body: "与配置方讨论多资产流动性、久期风险与宏观对冲的精选话题。",
    learnPost2Title: "管理人聚焦：数字资产中性策略",
    learnPost2Time: "每日更新",
    learnPost2Body: "数字资产团队风险笔记与运营更新的每日摘要。",
    learnPost3Title: "社区简报：运营与合规",
    learnPost3Time: "本周",
    learnPost3Body: "关于入驻清单、数据室与审计准备的问答。",
    complianceEyebrow: "合规优先",
    complianceTitle: "每个阶段的监管级控制。",
    complianceBody: "SOC2 就绪基础设施、地理围栏数据驻留与分层权限保护敏感信息。",
    complianceIdentityTitle: "身份与访问",
    complianceIdentityBody: "多因素认证、SSO/SAML 以及用于文件和 NDA 的安全保管库。",
    complianceMonitoringTitle: "监控",
    complianceMonitoringBody: "自动审计追踪、阈值告警以及传输与静态加密。",
    complianceGovernanceTitle: "治理",
    complianceGovernanceBody: "预配置政策与机构级尽调标准对齐。",
    contactEyebrow: "让我们沟通",
    contactTitle: "开启你的访问流程。",
    contactLead: "告诉我们你的投资委托或策略。我们的团队将协调数据室、尽调请求与安全访问。",
    contactResponseLabel: "响应时间",
    contactResponseMetric: "< 24 小时",
    contactCoverageLabel: "覆盖范围",
    contactCoverageMetric: "全球配置方",
    contactSecurityLabel: "安全性",
    contactSecurityMetric: "SOC2 就绪",
    contactNameLabel: "姓名",
    contactNamePlaceholder: "你的全名",
    contactEmailLabel: "邮箱",
    contactEmailPlaceholder: "you@firm.com",
    contactRoleLabel: "角色",
    contactRoleAria: "角色",
    contactRolePlaceholder: "选择你的角色",
    contactRoleAllocator: "配置方 / 投资人",
    contactRoleManager: "基金管理人",
    contactRoleOps: "运营 / 合规",
    contactNotesLabel: "备注",
    contactNotesPlaceholder: "委托规模、策略、时间安排",
    contactSubmit: "申请咨询",
    contactStatusSending: "发送中...",
    contactStatusSuccess: "我们已收到你的请求，将尽快回复。",
    contactStatusError: "暂时无法提交，请确认后端正在运行。",
    formNameLabel: "姓名",
    formNamePlaceholder: "你的全名",
    formFirmLabel: "机构",
    formFirmPlaceholderFamily: "家族办公室名称",
    formFirmPlaceholderManager: "机构名称",
    formStrategyLabel: "策略类型",
    formStrategyPlaceholderFamily: "宏观、信用、数字资产...",
    formStrategyPlaceholderManager: "信用、宏观、数字资产...",
    formAumLabel: "AUM",
    formAumPlaceholderFamily: "$500M",
    formAumPlaceholderManager: "$250M",
    formEmailLabel: "邮箱",
    formEmailPlaceholderFamily: "you@office.com",
    formEmailPlaceholderManager: "you@firm.com",
    formNotesLabel: "备注",
    formNotesPlaceholderFamily: "委托规模、目标策略、时间安排",
    formNotesPlaceholderManager: "委托重点、时间安排、目标",
    familyFormSubmit: "申请访问",
    formSubmit: "申请成为管理人",
    formStatusSending: "发送中...",
    formStatusSuccess: "已提交！",
    formStatusError: "暂时无法提交。",
    fundsLoading: "正在加载已验证基金...",
    fundsLoadError: "无法加载基金。请启动后端服务。",
    fundsEmpty: "暂无已验证基金。",
    fundsStatusVerified: "已验证",
    fundsSummaryDefault: "管理人正在验证中。",
    fundsHighlight1: "已验证业绩记录",
    fundsHighlight2: "每月报告",
    fundsHighlight3: "尽调就绪",
    fundsLabelAum: "AUM",
    fundsLabelYtd: "YTD",
    fundsLabelRisk: "风险",
    fundsLabelStrategyFallback: "多策略",
    fundsLabelDomicileFallback: "全球",
    insightsLoading: "正在加载洞察...",
    insightsLoadError: "无法加载洞察。请启动后端服务。",
    footerTagline: "为基金管理人和合格资本提供精英级连接。",
    footerPlatform: "平台",
    footerOverview: "概览",
    footerFeaturedFunds: "精选基金",
    footerIntelligence: "情报",
    footerCompany: "公司",
    footerAbout: "关于我们",
    footerCompliance: "合规",
    footerCareers: "招聘",
    footerContact: "联系",
    footerRequestCall: "预约通话",
    footerInvestorRelations: "投资者关系",
    footerRights: "© 2024 IGATES。保留所有权利。",
    footerPrivacy: "隐私与安全",
    managersHeroEyebrow: "面向管理人",
    managersHeroTitle: "为顶级策略打造的分销体系。",
    managersHeroLead: "通过 IGATES 的机构级基础设施连接全球已验证配置方。",
    managersHeroCta: "申请成为管理人",
    managersHeroTrust1: "覆盖宏观、信用与数字资产的配置方",
    managersHeroTrust2: "SOC2 就绪的数据交换",
    managersCardLabel1: "进行中的委托",
    managersCardCopy1: "合格配置方正在寻找差异化策略。",
    managersCardLabel2: "平均审核时间",
    managersCardCopy2: "自动化合规减少行政阻力。",
    managersBenefitsEyebrow: "平台优势",
    managersBenefitsTitle: "扩大配置方管道所需的一切。",
    managersBenefit1Title: "接入精选配置方",
    managersBenefit1Body: "定向介绍给积极配置你策略类型的合格 LP。",
    managersBenefit2Title: "安全数据室",
    managersBenefit2Body: "带水印与活动可视化的权限化数据室。",
    managersBenefit3Title: "合规流程",
    managersBenefit3Body: "内置 KYC、KYB 和治理检查，推动尽调不中断。",
    managersBenefit4Title: "嵌入式绩效情报",
    managersBenefit4Body: "自动化遥测向 LP 传递绩效、风险区间与因子漂移。",
    managersOnboardingEyebrow: "入驻流程",
    managersOnboardingTitle: "四步完成机构级分销。",
    managersStep1: "提交策略资料",
    managersStep2: "验证与合规",
    managersStep3: "数据集成与风险映射",
    managersStep4: "上线配置方市场",
    managersFormEyebrow: "管理人申请",
    managersFormTitle: "申请在 IGATES 分销。",
    managersFormLead: "提供策略详情，我们的团队将协调尽调与入驻。",
    managersFormResponseLabel: "响应时间",
    managersFormResponseMetric: "< 48 小时",
    managersFormSecurityLabel: "安全性",
    managersFormSecurityMetric: "合规优先",
    managersFormCoverageLabel: "覆盖范围",
    managersFormCoverageMetric: "全球配置方",
    familyHeroEyebrow: "家族办公室",
    familyHeroTitle: "面向现代家族办公室的机构访问。",
    familyHeroLead: "简化管理人发现、尽调与配置流程。",
    familyHeroCta: "申请访问",
    familyHeroTrust1: "配置方级报告",
    familyHeroTrust2: "私密数据流程",
    familyCardLabel1: "已审核策略",
    familyCardCopy1: "按委托标准定制的跨资产情报。",
    familyCardLabel2: "尽调文件",
    familyCardMetric2: "安全",
    familyCardCopy2: "具备审计准备的档案与自动更新。",
    familyWhyEyebrow: "为什么选择 IGATES",
    familyWhyTitle: "为投资负责人提供运营透明度。",
    familyWhy1Title: "已验证数据流",
    familyWhy1Body: "与托管、管理员及审计方对齐的报告。",
    familyWhy2Title: "审计就绪的报告",
    familyWhy2Body: "适用于投资委员会的完整归因与偏差拆解。",
    familyWhy3Title: "管理人评估整合",
    familyWhy3Body: "尽调跟踪、笔记与信号在同一工作区中并列展示。",
    familyWhy4Title: "风险区间分析",
    familyWhy4Body: "情景敏感区间确保配置保持在委托范围内。",
    familyCuratedEyebrow: "精选委托",
    familyCuratedTitle: "以配置方为先的策略视图。",
    familyMandate1: "宏观",
    familyMandate1Body: "全球宏观管理人，严格风险区间。",
    familyMandate2: "信用",
    familyMandate2Body: "事件驱动与结构化信用洞察，并具实时敞口检查。",
    familyMandate3: "数字资产",
    familyMandate3Body: "链上透明度与机构级托管信号。",
    familyMandate4: "系统化策略",
    familyMandate4Body: "因子敏感系统，监控模型漂移与容量。",
    familyFormEyebrow: "访问申请",
    familyFormTitle: "申请配置方访问。",
    familyFormLead: "告诉我们你的委托，我们将提供安全的管理人访问。",
    familyFormResponseLabel: "响应时间",
    familyFormResponseMetric: "< 24 小时",
    familyFormSecurityLabel: "安全性",
    familyFormSecurityMetric: "合规优先",
    familyFormCoverageLabel: "覆盖范围",
    familyFormCoverageMetric: "全球管理人",
  },
} as const;

export type LanguageKey = keyof typeof languageOptions;

export const MASTER_USER = {
  username: "Sebastian_ACY",
  password: "dB9(NP1O",
  role: "MasterUser",
} as const;

export const STRATEGY_OPTIONS = [
  { label: "Forex", value: "FOREX" },
  { label: "Indices & Macro", value: "INDICES_MACRO" },
  { label: "Commodities & Metales", value: "COMMODITIES_METALES" },
  { label: "Equities CFDs", value: "EQUITIES_CFD" },
  { label: "Crypto Assets", value: "CRYPTO_ASSETS" },
  { label: "Multi-Assets", value: "MULTI_ASSETS" },
];

export const SURVEY_DEFINITIONS = {
  Investor: [
    {
      id: "objective",
      label: "Investment Objective",
      type: "single",
      options: [
        { label: "Preservación de capital", value: "Preservación de capital" },
        { label: "Crecimiento moderado", value: "Crecimiento moderado" },
        { label: "Crecimiento agresivo", value: "Crecimiento agresivo" },
        { label: "Diversificación patrimonial", value: "Diversificación patrimonial" },
        { label: "Generación de ingresos", value: "Generación de ingresos" },
      ],
    },
    {
      id: "horizon",
      label: "Investment Horizon",
      type: "single",
      options: [
        { label: "Menos de 6 meses", value: "Menos de 6 meses" },
        { label: "Entre 6 meses y 1 año", value: "Entre 6 meses y 1 año" },
        { label: "1 a 3 años", value: "1 a 3 años" },
        { label: "Más de 3 años", value: "Más de 3 años" },
      ],
    },
    {
      id: "riskLevel",
      label: "Risk Tolerance",
      type: "single",
      options: [
        { label: "Conservador", value: "Conservador" },
        { label: "Moderado", value: "Moderado" },
        { label: "Balanceado", value: "Balanceado" },
        { label: "Agresivo", value: "Agresivo" },
      ],
    },
    {
      id: "strategyPreferences",
      label: "Preferred Strategy / Assets",
      type: "multi",
      options: STRATEGY_OPTIONS,
    },
    {
      id: "reportingFrequency",
      label: "Reporting Frequency",
      type: "single",
      options: [
        { label: "Mensual", value: "Mensual" },
        { label: "Trimestral", value: "Trimestral" },
        { label: "Solo eventos relevantes", value: "Solo eventos relevantes" },
      ],
    },
  ],
  "Fund Manager": [
    {
      id: "strategyType",
      label: "Primary Strategy / Assets",
      type: "single",
      options: STRATEGY_OPTIONS,
    },
    {
      id: "capitalStatus",
      label: "Capital Status",
      type: "single",
      options: [
        { label: "Opero con capital propio", value: "Opero con capital propio" },
        { label: "Opero con capital de terceros", value: "Opero con capital de terceros" },
        {
          label: "En transición hacia capital de terceros",
          value: "En transición hacia capital de terceros",
        },
        { label: "Track record en desarrollo", value: "Track record en desarrollo" },
      ],
    },
    {
      id: "trackRecordLength",
      label: "Verifiable Track Record Length",
      type: "single",
      options: [
        { label: "Menos de 12 meses", value: "Menos de 12 meses" },
        { label: "12 – 24 meses", value: "12 – 24 meses" },
        { label: "24 – 36 meses", value: "24 – 36 meses" },
        { label: "Más de 36 meses", value: "Más de 36 meses" },
      ],
    },
    {
      id: "operatingStructure",
      label: "Operating Structure",
      type: "single",
      options: [
        { label: "Cuenta segregada", value: "Cuenta segregada" },
        { label: "Managed Account (MAM / PAMM)", value: "Managed Account (MAM / PAMM)" },
        { label: "Vehículo privado (SPV / fondo privado)", value: "Vehículo privado (SPV / fondo privado)" },
        { label: "En proceso de estructuración", value: "En proceso de estructuración" },
      ],
    },
    {
      id: "strategyDescription",
      label: "Strategy Description",
      type: "text",
      prompt:
        "Describe tu estrategia en 2–4 líneas. Incluye instrumentos operados, horizonte típico y cómo gestionas el riesgo.",
    },
  ],
  "Family Office": [
    {
      id: "managementRole",
      label: "Desired Role in Investment Management",
      type: "single",
      options: [
        { label: "Supervisión estratégica", value: "Supervisión estratégica" },
        { label: "Selección activa de gestores", value: "Selección activa de gestores" },
        { label: "Delegación con reporting periódico", value: "Delegación con reporting periódico" },
      ],
    },
    {
      id: "diversificationLevel",
      label: "Desired Diversification Level",
      type: "single",
      options: [
        { label: "1–2 fondos", value: "1–2 fondos" },
        { label: "3–5 fondos", value: "3–5 fondos" },
        { label: "Más de 5 fondos", value: "Más de 5 fondos" },
      ],
    },
    {
      id: "strategyPreferences",
      label: "Preferred Strategy / Assets",
      type: "multi",
      options: STRATEGY_OPTIONS,
    },
    {
      id: "interactionLevel",
      label: "Interaction Level with Managers",
      type: "single",
      options: [
        { label: "Reportes únicamente", value: "Reportes únicamente" },
        { label: "Comunicación ocasional", value: "Comunicación ocasional" },
        { label: "Acceso directo y recurrente", value: "Acceso directo y recurrente" },
      ],
    },
    {
      id: "reportingCustomization",
      label: "Reporting Customization Level",
      type: "single",
      options: [
        { label: "Básico", value: "Básico" },
        { label: "Personalizado", value: "Personalizado" },
        { label: "Totalmente a medida", value: "Totalmente a medida" },
      ],
    },
  ],
} as const;

export const STORAGE_KEYS = {
  profiles: "igatesUserProfiles",
  session: "igatesCurrentSession",
  notifications: "igatesMasterNotifications",
  fundApplications: "igatesFundApplications",
  preferredLanguage: "preferredLanguage",
};

export const baseVerifiedFunds = [
  {
    id: "brenna-funding",
    name: "Brenna Funding",
    country: "Portugal",
    logoLabel: "BF",
    region: "Europa",
    strategy: "Private Credit",
    riskLevel: "Bajo",
    yearProfit: 7.8,
    maxDrawdown: 4.1,
    winRate: 61,
    volatility: 5.2,
    aum: "€120M",
    description:
      "Vehículo de crédito privado con foco en preservación de capital y liquidez trimestral.",
  },
  {
    id: "xetra-capital",
    name: "Xetra Capital",
    country: "Suiza",
    logoLabel: "XC",
    region: "Europa",
    strategy: "Macro",
    riskLevel: "Medio",
    yearProfit: 11.2,
    maxDrawdown: 6.9,
    winRate: 58,
    volatility: 7.4,
    aum: "CHF 210M",
    description: "Estrategia macro institucional con coberturas dinámicas y foco en tasas y FX.",
  },
  {
    id: "capital-management",
    name: "Capital Management",
    country: "Argentina",
    logoLabel: "CM",
    region: "LatAm",
    strategy: "Multi-Strategy",
    riskLevel: "Medio",
    yearProfit: 9.6,
    maxDrawdown: 7.8,
    winRate: 55,
    volatility: 8.1,
    aum: "USD 95M",
    description: "Asignación táctica con sesgo a crédito regional y coberturas cambiarias.",
  },
  {
    id: "bullish-investment",
    name: "Bullish Investment",
    country: "México",
    logoLabel: "BI",
    region: "LatAm",
    strategy: "Equity Long/Short",
    riskLevel: "Alto",
    yearProfit: 13.4,
    maxDrawdown: 10.6,
    winRate: 57,
    volatility: 10.9,
    aum: "USD 140M",
    description: "Cartera long/short con enfoque en consumo y tecnología regional.",
  },
  {
    id: "capital-grow",
    name: "Capital Grow Investment",
    country: "Colombia",
    logoLabel: "CG",
    region: "LatAm",
    strategy: "Real Assets",
    riskLevel: "Bajo",
    yearProfit: 8.4,
    maxDrawdown: 5.2,
    winRate: 60,
    volatility: 6.1,
    aum: "USD 110M",
    description: "Estrategia de activos reales con flujo estable y estructura institucional.",
  },
];

const seedCompletedAt = "2024-05-01T12:00:00.000Z";

export const DEFAULT_FUND_MANAGER_PROFILES: UserProfile[] = baseVerifiedFunds.map((fund, index) => {
  const managerProfile = {
    strategyType: fund.strategy,
    strategyTypeLabel: fund.strategy,
    capitalStatus: "Opero con capital de terceros",
    trackRecordLength: "Más de 36 meses",
    operatingStructure: "Vehículo privado (SPV / fondo privado)",
    strategyDescription: fund.description,
    status: "verified" as const,
  };
  const isBrennaFund = fund.id === "brenna-funding";

  return {
    id: `fund-manager-${fund.id}`,
    fullName: isBrennaFund ? "Brenna Goncalvez" : `${fund.name} Management`,
    email: isBrennaFund ? "brenna.investtrader@gmail.com" : `manager+${fund.id}@igatesfunds.com`,
    phone: "+00 000 000 000",
    country: fund.country,
    role: "Fund Manager",
    password: isBrennaFund ? "BrennaFG_2025" : `Fund${index + 1}!IGATES`,
    fundId: fund.id,
    onboarding: {
      role: "Fund Manager",
      completedAt: seedCompletedAt,
      fundManagerProfile: managerProfile,
      fundId: fund.id,
    },
    fundManagerProfile: managerProfile,
  };
});

export const countryFlags: Record<string, string> = {
  Portugal: "🇵🇹",
  Suiza: "🇨🇭",
  Argentina: "🇦🇷",
  México: "🇲🇽",
  Colombia: "🇨🇴",
};

export function getStrategyLabel(value: string) {
  return STRATEGY_OPTIONS.find((option) => option.value === value)?.label ?? value;
}

export function formatStrategyList(values?: string[]) {
  if (!values || !values.length) return "—";
  return values.map((value) => getStrategyLabel(value)).join(", ");
}

export function getFundLogoLabel(name = "") {
  return name
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((word) => word[0]?.toUpperCase())
    .join("");
}

export function formatPercent(value?: number | null, decimals = 1) {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";
  const sign = value > 0 ? "+" : "";
  return `${sign}${value.toFixed(decimals)}%`;
}

export function formatNumber(value?: number | null, suffix = "", decimals = 1) {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";
  return `${value.toFixed(decimals)}${suffix}`;
}
